### ISSUE TITLE
Ops App - 2024 Checkboxes

### ISSUE THREAD

**Issue by JenniferBacker** [acaprime/Ops-app#1] opened 2024-04-11 19:35 UTC
Hi Blake!  For 2024, can you please add those years to Ops App in the "Create New Client" page as well as the separate page where you're just selecting tax years for the FreshDesk cases too.  Thanks!

**Comment by blakepatteson** [comment] 2024-04-12 13:28
Thanks @JenniferBacker! I will get this very soon.

Also - just FYI - this code repository doesn't exist, so I moved the issue to the "acaprime/acaprime-ops" repo where the code actually lives. 

Closing this one as a duplicate of this now : 
    https://github.com/acaprime/acaprime-ops/issues/181

**Closed by blakepatteson** 2024-04-12 13:28 UTC
